In [3]:
import pandas as pd

In [4]:
New_York = pd.read_csv('../New_York/sqf-2017.csv')

In [30]:
New_York[['FRISKED_FLAG','SUSPECT_ARRESTED_FLAG']]

      FRISKED_FLAG SUSPECT_ARRESTED_FLAG
0                N                     N
1                N                     N
2                N                     N
3                Y                     N
4                N                     N
5                Y                     Y
6                N                     N
7                Y                     N
8                Y                     N
9                Y                     Y
10               Y                     N
11               Y                     N
12               Y                     N
13               N                     N
14               N                     N
15               Y                     N
16               Y                     Y
17               N                     N
18               Y                     N
19               Y                     Y
20               Y                     N
21               N                     N
22               N                     N
23               N                     N
24               N                     N
25               N                     N
26               N                     N
27               Y                     Y
28               Y                     N
29               N                     N
...            ...                   ...
11599            Y                     Y
11600            Y                     Y
11601            Y                     Y
11602            N                     Y
11603            Y                     Y
11604            Y                     Y
11605            Y                     Y
11606            N                     N
11607            N                     N
11608            N                     N
11609            N                     Y
11610            Y                     N
11611            N                     Y
11612            N                     N
11613            N                     N
11614            N                     N
11615            N                     N
11616            Y                     N
11617            Y                     N
11618            N                     Y
11619            N                     Y
11620            Y                     N
11621            Y                     Y
11622            N                     N
11623            Y                     N
11624            Y                     Y
11625            Y                     N
11626            Y                     Y
11627            N                     Y
11628            N                     Y

[11629 rows x 2 columns]

In [26]:
New_York2 = pd.read_csv('../New_York/sqf-2016.csv')

C:\Users\shawna06\Anaconda3\lib\site-packages\IPython\core\interactiveshell.py:2698: DtypeWarning: Columns (0,1,2,3,4,8,18,19,73,74,84,85,86,103,110,111) have mixed types. Specify dtype option on import or set low_memory=False.
  interactivity=interactivity, compiler=compiler, result=result)

In [5]:
New_York2.head()

,year,pct,ser_num,datestop,timestop,recstat,inout,trhsloc,perobs,crimsusp,...,zip,addrpct,sector,beat,post,xcoord,ycoord,dettypCM,lineCM,detailCM
0,2016,41,22,2072016,100,A,O,P,1,BURG,...,,41,B,2,,1013353,234000,CM,1,14
1,2016,10,22,2182016,30,1,O,P,8,MISDEMEANOR,...,,10,D,,,983478,212373,CM,1,28
2,2016,66,1,1012016,30,1,I,P,2,FEL,...,,66,F,,,988340,172111,CM,1,9
3,2016,47,18,1012016,40,1,O,H,1,FEL,...,,47,C,,,,,CM,1,20
4,2016,79,1,1012016,50,1,O,P,3,D.W.I.,...,,79,G,4,,998197,187413,CM,1,112

In [28]:
list(New_York.columns)

['STOP_FRISK_ID',
 'STOP_FRISK_DATE',
 'STOP_FRISK_TIME',
 'YEAR2',
 'MONTH2',
 'DAY2',
 'STOP_WAS_INITIATED',
 'SPRINT_NUMBER',
 'RECORD_STATUS_CODE',
 'ISSUING_OFFICER_RANK',
 'ISSUING_OFFICER_COMMAND_CODE',
 'SUPERVISING_OFFICER_RANK',
 'SUPERVISING_OFFICER_COMMAND_CODE',
 'SUPERVISING_ACTION_CORRESPONDING_ACTIVITY_LOG_ENTRY_REVIEWED',
 'LOCATION_IN_OUT_CODE',
 'JURISDICTION_CODE',
 'JURISDICTION_DESCRIPTION',
 'OBSERVED_DURATION_MINUTES',
 'SUSPECTED_CRIME_DESCRIPTION',
 'STOP_DURATION_MINUTES',
 'OFFICER_EXPLAINED_STOP_FLAG',
 'OFFICER_NOT_EXPLAINED_STOP_DESCRIPTION',
 'OTHER_PERSON_STOPPED_FLAG',
 'SUSPECT_ARRESTED_FLAG',
 'SUSPECT_ARREST_NUMBER',
 'SUSPECT_ARREST_OFFENSE',
 'SUMMONS_ISSUED_FLAG',
 'SUMMONS_NUMBER',
 'SUMMONS_OFFENSE_DESCRIPTION',
 'OFFICER_IN_UNIFORM_FLAG',
 'ID_CARD_IDENTIFIES_OFFICER_FLAG',
 'SHIELD_IDENTIFIES_OFFICER_FLAG',
 'VERBAL_IDENTIFIES_OFFICER_FLAG',
 'FRISKED_FLAG',
 'SEARCHED_FLAG',
 'OTHER_CONTRABAND_FLAG',
 'FIREARM_FLAG',
 'KNIFE_CUTTER_FLAG',
 'OTHER_WEAPON_FLAG',
 'WEAPON_FOUND_FLAG',
 'PHYSICAL_FORCE_CEW_FLAG',
 'PHYSICAL_FORCE_DRAW_POINT_FIREARM_FLAG',
 'PHYSICAL_FORCE_HANDCUFF_SUSPECT_FLAG',
 'PHYSICAL_FORCE_OC_SPRAY_USED_FLAG',
 'PHYSICAL_FORCE_OTHER_FLAG',
 'PHYSICAL_FORCE_RESTRAINT_USED_FLAG',
 'PHYSICAL_FORCE_VERBAL_INSTRUCTION_FLAG',
 'PHYSICAL_FORCE_WEAPON_IMPACT_FLAG',
 'BACKROUND_CIRCUMSTANCES_VIOLENT_CRIME_FLAG',
 'BACKROUND_CIRCUMSTANCES_SUSPECT_KNOWN_TO_CARRY_WEAPON_FLAG',
 'SUSPECTS_ACTIONS_CASING_FLAG',
 'SUSPECTS_ACTIONS_CONCEALED_POSSESSION_WEAPON_FLAG',
 'SUSPECTS_ACTIONS_DECRIPTION_FLAG',
 'SUSPECTS_ACTIONS_DRUG_TRANSACTIONS_FLAG',
 'SUSPECTS_ACTIONS_IDENTIFY_CRIME_PATTERN_FLAG',
 'SUSPECTS_ACTIONS_LOOKOUT_FLAG',
 'SUSPECTS_ACTIONS_OTHER_FLAG',
 'SUSPECTS_ACTIONS_PROXIMITY_TO_SCENE_FLAG',
 'SEARCH_BASIS_ADMISSION_FLAG',
 'SEARCH_BASIS_CONSENT_FLAG',
 'SEARCH_BASIS_HARD_OBJECT_FLAG',
 'SEARCH_BASIS_INCIDENTAL_TO_ARREST_FLAG',
 'SEARCH_BASIS_OTHER_FLAG',
 'SEARCH_BASIS_OUTLINE_FLAG',
 'DEMEANOR_CODE',
 'DEMEANOR_OF_PERSON_STOPPED',
 'SUSPECT_REPORTED_AGE',
 'SUSPECT_SEX',
 'SUSPECT_RACE_DESCRIPTION',
 'SUSPECT_HEIGHT',
 'SUSPECT_WEIGHT',
 'SUSPECT_BODY_BUILD_TYPE',
 'SUSPECT_EYE_COLOR',
 'SUSPECT_HAIR_COLOR',
 'SUSPECT_OTHER_DESCRIPTION',
 'STOP_LOCATION_PRECINCT',
 'STOP_LOCATION_SECTOR_CODE',
 'STOP_LOCATION_APARTMENT',
 'STOP_LOCATION_FULL_ADDRESS',
 'STOP_LOCATION_PREMISES_NAME',
 'STOP_LOCATION_STREET_NAME',
 'STOP_LOCATION_X',
 'STOP_LOCATION_Y',
 'STOP_LOCATION_ZIP_CODE',
 'STOP_LOCATION_PATROL_BORO_NAME',
 'STOP_LOCATION_BORO_NAME']

In [7]:
list(New_York2.columns)

['year',
 'pct',
 'ser_num',
 'datestop',
 'timestop',
 'recstat',
 'inout',
 'trhsloc',
 'perobs',
 'crimsusp',
 'perstop',
 'typeofid',
 'explnstp',
 'othpers',
 'arstmade',
 'arstoffn',
 'sumissue',
 'sumoffen',
 'compyear',
 'comppct',
 'offunif',
 'officrid',
 'frisked',
 'searched',
 'contrabn',
 'adtlrept',
 'pistol',
 'riflshot',
 'asltweap',
 'knifcuti',
 'machgun',
 'othrweap',
 'pf_hands',
 'pf_wall',
 'pf_grnd',
 'pf_drwep',
 'pf_ptwep',
 'pf_baton',
 'pf_hcuff',
 'pf_pepsp',
 'pf_other',
 'radio',
 'ac_rept',
 'ac_inves',
 'rf_vcrim',
 'rf_othsw',
 'ac_proxm',
 'rf_attir',
 'cs_objcs',
 'cs_descr',
 'cs_casng',
 'cs_lkout',
 'rf_vcact',
 'cs_cloth',
 'cs_drgtr',
 'ac_evasv',
 'ac_assoc',
 'cs_furtv',
 'rf_rfcmp',
 'ac_cgdir',
 'rf_verbl',
 'cs_vcrim',
 'cs_bulge',
 'cs_other',
 'ac_incid',
 'ac_time',
 'rf_knowl',
 'ac_stsnd',
 'ac_other',
 'sb_hdobj',
 'sb_outln',
 'sb_admis',
 'sb_other',
 'repcmd',
 'revcmd',
 'rf_furt',
 'rf_bulg',
 'offverb',
 'offshld',
 'forceuse',
 'sex',
 'race',
 'dob',
 'age',
 'ht_feet',
 'ht_inch',
 'weight',
 'haircolr',
 'eyecolor',
 'build',
 'othfeatr',
 'addrtyp',
 'rescode',
 'premtype',
 'premname',
 'addrnum',
 'stname',
 'stinter',
 'crossst',
 'aptnum',
 'city',
 'state',
 'zip',
 'addrpct',
 'sector',
 'beat',
 'post',
 'xcoord',
 'ycoord',
 'dettypCM',
 'lineCM',
 'detailCM']

In [10]:
New_York2['race'].unique()

array(['B', 'W', 'P', 'A', 'Q', 'U', 'Z', 'I', ' '], dtype=object)

In [12]:
New_York2['frisked'].isnull()

0        False
1        False
2        False
3        False
4        False
5        False
6        False
7        False
8        False
9        False
10       False
11       False
12       False
13       False
14       False
15       False
16       False
17       False
18       False
19       False
20       False
21       False
22       False
23       False
24       False
25       False
26       False
27       False
28       False
29       False
         ...
12375    False
12376    False
12377    False
12378    False
12379    False
12380    False
12381    False
12382    False
12383    False
12384    False
12385    False
12386    False
12387    False
12388    False
12389    False
12390    False
12391    False
12392    False
12393    False
12394    False
12395    False
12396    False
12397    False
12398    False
12399    False
12400    False
12401    False
12402    False
12403    False
12404    False
Name: frisked, Length: 12405, dtype: bool